### ISSUE TITLE
USER STORY: request annual leave

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#10]
As a **member of staff** I can **request annual leave** so that **received_benefit**

# Acceptance Criteria

 - Acceptance Criteria 1
 - Acceptance Criteria 2

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Notes / Resources

**Comment by Craigj915** [comment]
done in ->
[](https://github.com/mjjstockman/TDA-SAC/tree/15-user-story-approve-leave-request)
