### ISSUE TITLE
USER STORY: check if leave request has been approved

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#13]
As a **Member of Staff** I can **see if my leave requests have been approved or not** so that **received_benefit**

# Acceptance Criteria

 - Acceptance Criteria 1
 - Acceptance Criteria 2

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Notes / Resources

**Comment by Craigj915** [comment]
done in ->
[user-story-approve-leave-request](https://github.com/mjjstockman/TDA-SAC/tree/15-user-story-approve-leave-request)

user gets notifications when request is approved or denied
