### ISSUE TITLE
USER STORY: add staff to a team

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#18]
As a **system admin** I can **Add team members to a team** so that **received_benefit**

# Acceptance Criteria

 - Acceptance Criteria 1
 - Acceptance Criteria 2

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Notes / Resources

**Comment by Craigj915** [comment]
Done -
[44-user-story-get-teams-etc](https://github.com/mjjstockman/TDA-SAC/tree/44-user-story-get-teams-etc)
