### ISSUE TITLE
USER STORY: add staff

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/TDA-SAC#26]
As a **Manager** I can **add new members of staff** so that **received_benefit**

# Acceptance Criteria

 - Acceptance Criteria 1
 - Acceptance Criteria 2

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

# Notes / Resources

**Comment by Craigj915** [comment]
Done -
[44-user-story-get-teams-etc](https://github.com/mjjstockman/TDA-SAC/tree/44-user-story-get-teams-etc)
