### ISSUE TITLE
USER STORY: user management

### ISSUE THREAD

**Issue by Craigj915** [mjjstockman/TDA-SAC#7]
As a **manager** I can **check users roles** so that **I can allocate higher privilege and access**
As an **admin** I can **moderate users** so that **I can allocate roles and revoke/allow access**

# Acceptance Criteria

 - There are clearly defined roles linked to each user
 - Roles will give different privilege to users (Admin - highest privilege, can revoke user access and change user roles etc.)

# Tasks

- [x] Task 1 - Add roles
- [x] Find out most common role and set that as default for model instantiation??

# Notes / Resources
- Instructor
- Member of Staff
- Course manager
- Director
- Marketing / admissions staff
- Manager
- System admin
- User

**Comment by mjjstockman** [comment]
Nice one Ash! Not too sure of the best way to do it, and this will be good practice for us talk about in the standup tmz...... i rekn let's Refractor the US (User Stories) above into 2 seperate ones. REMINDER for stand up tmoz, chat about conventions to use in project, eg: how use kanban, coding style conventions (all set linters to agreed styles??), line length, etc.

**Comment by mjjstockman** [comment]
REMINDER: discuss app ideas in standup, discuaa best way for us to add thoughts/rubber duck each other

**Comment by mjjstockman** [comment]
find best tool to add and share sprints together. ASK ALFIE

**Comment by mjjstockman** [comment]
NOTE: have added default user role to US task. Ask tmoz if want me to go over this?

**Comment by Craigj915** [comment]
Login checks for role 
sends to page depending on role
